CREATE TABLE calendar (
instance_id INT NOT NULL  generated always as identity ,
name VARCHAR( 100 ) NOT NULL ,
location VARCHAR( 100 ) NOT NULL ,
start_time VARCHAR( 100 ) NOT NULL ,
end_time VARCHAR( 100 ) NOT NULL ,
instance_date VARCHAR( 100 ) NOT NULL ,
PRIMARY KEY ( instance_id ));


INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('WPC Meeting', 'Chesapeake, VA', 'Mar 11 2011', '3PT', '8PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Strategy Meeting', 'San Jose, CA', 'Mar 05 2011', '8PT', '10PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Google Demo', 'Tucson, AZ', 'Mar 20 2011', '4PT', '9PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Project Planning', 'El Paso, TX', 'Mar 07 2011', '4PT', '5PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Strategy Meeting', 'Stockton, CA', 'Mar 29 2011', '9PT', '10PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Strategy Meeting', 'Jersey City, NJ', 'Mar 09 2011', '3PT', '10PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Project Planning', 'Garland, TX', 'Mar 15 2011', '3PT', '6PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Budget Meeting', 'Scottsdale, AZ', 'Mar 26 2011', '2PT', '10PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Budget Meeting', 'San Antonio, TX', 'Mar 29 2011', '4PT', '6PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('WPC Meeting', 'San Bernardino, CA', 'Mar 30 2011', '5PT', '8PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Budget Meeting', 'Stockton, CA', 'Mar 09 2011', '10PT', '11PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Google Demo', 'Memphis, TN', 'Mar 27 2011', '7PT', '9PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Project Planning', 'New Orleans, LA', 'Mar 29 2011', '7PT', '9PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('WPC Meeting', 'Kansas City, MO', 'Mar 24 2011', '9PT', '10PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Google Demo', 'Fort Worth, TX', 'Mar 07 2011', '3PT', '5PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Project Planning', 'Glendale, AZ', 'Mar 07 2011', '3PT', '6PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Project Planning', 'Sacramento, CA', 'Mar 19 2011', '1PT', '2PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('WPC Meeting', 'Indianapolis, IN', 'Mar 16 2011', '4PT', '9PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('WPC Meeting', 'Austin, TX', 'Mar 09 2011', '10PT', '11PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Project Planning', 'Corpus Christi, TX', 'Mar 21 2011', '5PT', '10PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Budget Meeting', 'Houston, TX', 'Mar 09 2011', '7PT', '8PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Google Demo', 'Fremont, CA', 'Mar 02 2011', '10PT', '11PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Project Planning', 'Fresno, CA', 'Mar 13 2011', '4PT', '5PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('WPC Meeting', 'Fremont, CA', 'Mar 01 2011', '9PT', '10PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Scrum Session', 'Durham, NC', 'Mar 29 2011', '5PT', '6PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Project Planning', 'Minneapolis, MN', 'Mar 18 2011', '5PT', '10PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Google Demo', 'Jacksonville, FL', 'Mar 23 2011', '3PT', '10PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Strategy Meeting', 'Miami, FL', 'Mar 20 2011', '4PT', '10PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Budget Meeting', 'Glendale, CA', 'Mar 28 2011', '1PT', '5PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Budget Meeting', 'Wichita, KS', 'Mar 10 2011', '1PT', '3PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Project Planning', 'Lubbock, TX', 'Mar 11 2011', '1PT', '3PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Project Planning', 'Akron, OH', 'Mar 18 2011', '9PT', '10PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('WPC Meeting', 'Detroit, MI', 'Mar 04 2011', '3PT', '8PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Strategy Meeting', 'Wichita, KS', 'Mar 02 2011', '7PT', '10PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Scrum Session', 'Lexington-Fayette, KY', 'Mar 14 2011', '9PT', '10PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Scrum Session', 'Nashville-Davidson, TN', 'Mar 07 2011', '7PT', '9PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Google Demo', 'Reno, NV', 'Mar 01 2011', '4PT', '5PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('WPC Meeting', 'Milwaukee, WI', 'Mar 01 2011', '5PT', '6PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Google Demo', 'Oakland, CA', 'Mar 26 2011', '2PT', '3PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Scrum Session', 'Cleveland, OH', 'Mar 18 2011', '1PT', '6PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Strategy Meeting', 'Durham, NC', 'Mar 26 2011', '3PT', '8PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Strategy Meeting', 'Detroit, MI', 'Mar 07 2011', '2PT', '4PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Strategy Meeting', 'Jacksonville, FL', 'Mar 18 2011', '4PT', '8PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Scrum Session', 'Chesapeake, VA', 'Mar 28 2011', '1PT', '8PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('WPC Meeting', 'Tulsa, OK', 'Mar 29 2011', '3PT', '10PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Budget Meeting', 'Scottsdale, AZ', 'Mar 22 2011', '7PT', '9PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Project Planning', 'Norfolk, VA', 'Mar 14 2011', '9PT', '10PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Scrum Session', 'Riverside, CA', 'Mar 08 2011', '2PT', '6PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Google Demo', 'Las Vegas, NV', 'Mar 04 2011', '4PT', '8PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Strategy Meeting', 'Arlington, VA', 'Mar 29 2011', '9PT', '10PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Google Demo', 'Minneapolis, MN', 'Mar 16 2011', '2PT', '3PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Google Demo', 'Lexington-Fayette, KY', 'Mar 19 2011', '6PT', '10PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Scrum Session', 'Philadelphia, PA', 'Mar 12 2011', '7PT', '10PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Project Planning', 'Durham, NC', 'Mar 28 2011', '8PT', '10PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Project Planning', 'Sacramento, CA', 'Mar 29 2011', '10PT', '11PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Budget Meeting', 'Durham, NC', 'Mar 22 2011', '5PT', '7PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Scrum Session', 'Garland, TX', 'Mar 20 2011', '2PT', '9PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('WPC Meeting', 'Chandler, AZ', 'Mar 14 2011', '2PT', '6PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('WPC Meeting', 'Los Angeles, CA', 'Mar 27 2011', '10PT', '11PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Strategy Meeting', 'Norfolk, VA', 'Mar 30 2011', '5PT', '8PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Google Demo', 'Wichita, KS', 'Mar 17 2011', '7PT', '8PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Google Demo', 'Washington, DC', 'Mar 16 2011', '9PT', '10PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Budget Meeting', 'Montgomery, AL', 'Mar 14 2011', '3PT', '7PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('WPC Meeting', 'Tampa, FL', 'Mar 29 2011', '10PT', '11PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Google Demo', 'San Bernardino, CA', 'Mar 26 2011', '10PT', '11PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Strategy Meeting', 'Sacramento, CA', 'Mar 13 2011', '6PT', '9PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('WPC Meeting', 'Anaheim, CA', 'Mar 01 2011', '1PT', '3PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Strategy Meeting', 'Omaha, NE', 'Mar 03 2011', '5PT', '10PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Strategy Meeting', 'Charlotte, NC', 'Mar 18 2011', '10PT', '11PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Strategy Meeting', 'Miami, FL', 'Mar 25 2011', '2PT', '7PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('WPC Meeting', 'San Bernardino, CA', 'Mar 05 2011', '3PT', '9PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('WPC Meeting', 'Raleigh, NC', 'Mar 06 2011', '5PT', '9PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Strategy Meeting', 'Baton Rouge, LA', 'Mar 07 2011', '8PT', '10PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Scrum Session', 'Toledo, OH', 'Mar 05 2011', '4PT', '9PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Budget Meeting', 'Riverside, CA', 'Mar 20 2011', '1PT', '3PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('WPC Meeting', 'Arlington, VA', 'Mar 19 2011', '10PT', '11PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Budget Meeting', 'Akron, OH', 'Mar 15 2011', '10PT', '11PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Strategy Meeting', 'Kansas City, MO', 'Mar 25 2011', '8PT', '9PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Scrum Session', 'Orlando, FL', 'Mar 12 2011', '4PT', '5PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Budget Meeting', 'Rochester, NY', 'Mar 29 2011', '8PT', '9PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('WPC Meeting', 'Charlotte, NC', 'Mar 22 2011', '7PT', '10PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Google Demo', 'Tulsa, OK', 'Mar 12 2011', '4PT', '7PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('WPC Meeting', 'Miami, FL', 'Mar 13 2011', '1PT', '7PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Project Planning', 'Shreveport, LA', 'Mar 10 2011', '4PT', '6PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Strategy Meeting', 'Santa Ana, CA', 'Mar 15 2011', '8PT', '9PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Project Planning', 'Fort Wayne, IN', 'Mar 16 2011', '5PT', '10PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('WPC Meeting', 'Fresno, CA', 'Mar 25 2011', '7PT', '10PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Google Demo', 'Seattle, WA', 'Mar 01 2011', '1PT', '5PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Project Planning', 'Tampa, FL', 'Mar 28 2011', '1PT', '7PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('WPC Meeting', 'Lubbock, TX', 'Mar 01 2011', '10PT', '11PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Budget Meeting', 'Columbus, OH', 'Mar 23 2011', '9PT', '10PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Google Demo', 'Norfolk, VA', 'Mar 07 2011', '2PT', '8PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Scrum Session', 'Los Angeles, CA', 'Mar 18 2011', '4PT', '6PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Google Demo', 'Los Angeles, CA', 'Mar 30 2011', '9PT', '10PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Budget Meeting', 'Oklahoma City, OK', 'Mar 29 2011', '8PT', '10PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Budget Meeting', 'Minneapolis, MN', 'Mar 02 2011', '4PT', '9PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Scrum Session', 'North Hempstead, NY', 'Mar 14 2011', '7PT', '9PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('WPC Meeting', 'Oakland, CA', 'Mar 18 2011', '4PT', '5PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('WPC Meeting', 'Cleveland, OH', 'Mar 25 2011', '4PT', '5PT');
INSERT INTO calendar (name, location, instance_date, start_time, end_time)	VALUES ('Scrum Session', 'Garland, TX', 'Mar 21 2011', '7PT', '10PT');
